repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs/blob/main
repository: dynamsoft-docs/code-parser-docs
docFullPath: https://www.dynamsoft.com/code-parser/docs/core
firstLevelUrl: /code-parser/docs/core/
docHomePage: /code-parser/docs/core/introduction/

introduction: /code-parser/docs/core/introduction/

cpp: /code-parser/docs/server/programming/cplusplus/
cpp_release_notes: /code-parser/docs/server/programming/cplusplus/release-notes/


js: /code-parser/docs/js/programming/javascript/
js_release_notes: /code-parser/docs/js/programming/javascript/release-notes/

release-notes: /code-parser/docs/core/release-notes/
code_types: /code-parser/docs/core/code-types/

enumerations: /capture-vision/docs/core/enums/
parameters: /capture-vision/docs/core/parameters/
parameters_dcp: /code-parser/docs/core/parameters/
parameters_reference: /capture-vision/docs/core/parameters/reference/
parameters_reference_dcp: /code-parser/docs/core/parameters/reference/
license: /capture-vision/docs/core/license/


assets: /code-parser/docs/core/assets/
edit_icon: /code-parser/docs/core/assets/img-icon/edit-icon.png
smile_icon: /code-parser/docs/core/assets/img-icon/icon-smile.png
sad_icon: /code-parser/docs/core/assets/img-icon/icon-sad.png

useVersionTree: true

baseurl: "/code-parser/docs/core"
plugins:
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "" 
    values: 
      docRootName: "Code Parser" 
      docHomePage: "/code-parser/docs/core/introduction/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root

